In [1]:
pip install mysql-connector-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
from mysql.connector import connect
from getpass import getpass #pour le mot de passe SQL 
import pandas as pd

In [3]:
db = connect(
            host = "localhost",
            user = "root",
            passwd = getpass("Enter your password please"),
            database = "sakila")

In [4]:
#Create a query or queries to extract the information you think may be relevant for building the prediction model. It should include some film features and some rental features.
#Read the data into a Pandas dataframe.

In [5]:
query_1 = "select * from film_rental_1"
df = pd.read_sql_query(query_1,db)
df

C:\Users\Selma\AppData\Local\Temp\ipykernel_3612\3177947812.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_1,db)


title rating  rental_rate  length  film_id  inventory_id  \
0      ACADEMY DINOSAUR     PG         0.99      86        1             1   
1      ACADEMY DINOSAUR     PG         0.99      86        1             1   
2      ACADEMY DINOSAUR     PG         0.99      86        1             1   
3      ACADEMY DINOSAUR     PG         0.99      86        1             2   
4      ACADEMY DINOSAUR     PG         0.99      86        1             2   
...                 ...    ...          ...     ...      ...           ...   
16039         ZORRO ARK  NC-17         4.99      50     1000          4581   
16040         ZORRO ARK  NC-17         4.99      50     1000          4581   
16041         ZORRO ARK  NC-17         4.99      50     1000          4581   
16042         ZORRO ARK  NC-17         4.99      50     1000          4581   
16043         ZORRO ARK  NC-17         4.99      50     1000          4581   

       rental_id         rental_date         return_date  
0           4863 2005-07-08 19:03:15 2005-07-11 21:29:15  
1          11433 2005-08-02 20:13:10 2005-08-11 21:35:10  
2          14714 2005-08-21 21:27:43 2005-08-30 22:26:43  
3            972 2005-05-30 20:21:07 2005-06-06 00:36:07  
4           2117 2005-06-17 20:24:00 2005-06-23 17:45:00  
...          ...                 ...                 ...  
16039        711 2005-05-29 03:49:03 2005-05-31 08:29:03  
16040       1493 2005-06-15 21:50:32 2005-06-17 01:02:32  
16041       6712 2005-07-12 13:24:47 2005-07-20 09:35:47  
16042       9701 2005-07-31 07:32:21 2005-08-01 05:07:21  
16043      12894 2005-08-19 03:49:28 2005-08-25 01:51:28  

[16044 rows x 9 columns]

In [6]:
#Create a query to get the list of films and a boolean indicating if it was rented last month. This would be our target variable.

In [7]:
query_2 = "select * from rented_last_month_"
df_2 = pd.read_sql_query(query_2,db)
df_2

C:\Users\Selma\AppData\Local\Temp\ipykernel_3612\3626275099.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_2 = pd.read_sql_query(query_2,db)


title rating  rental_rate  length  film_id  inventory_id  \
0      ACADEMY DINOSAUR     PG         0.99      86        1             1   
1      ACADEMY DINOSAUR     PG         0.99      86        1             1   
2      ACADEMY DINOSAUR     PG         0.99      86        1             1   
3      ACADEMY DINOSAUR     PG         0.99      86        1             2   
4      ACADEMY DINOSAUR     PG         0.99      86        1             2   
...                 ...    ...          ...     ...      ...           ...   
16039         ZORRO ARK  NC-17         4.99      50     1000          4581   
16040         ZORRO ARK  NC-17         4.99      50     1000          4581   
16041         ZORRO ARK  NC-17         4.99      50     1000          4581   
16042         ZORRO ARK  NC-17         4.99      50     1000          4581   
16043         ZORRO ARK  NC-17         4.99      50     1000          4581   

       rental_id         rental_date         return_date rented_last_month  
0           4863 2005-07-08 19:03:15 2005-07-11 21:29:15                 0  
1          11433 2005-08-02 20:13:10 2005-08-11 21:35:10                 1  
2          14714 2005-08-21 21:27:43 2005-08-30 22:26:43                 1  
3            972 2005-05-30 20:21:07 2005-06-06 00:36:07                 0  
4           2117 2005-06-17 20:24:00 2005-06-23 17:45:00                 0  
...          ...                 ...                 ...               ...  
16039        711 2005-05-29 03:49:03 2005-05-31 08:29:03                 0  
16040       1493 2005-06-15 21:50:32 2005-06-17 01:02:32                 0  
16041       6712 2005-07-12 13:24:47 2005-07-20 09:35:47                 0  
16042       9701 2005-07-31 07:32:21 2005-08-01 05:07:21                 0  
16043      12894 2005-08-19 03:49:28 2005-08-25 01:51:28                 1  

[16044 rows x 10 columns]

In [8]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16044 entries, 0 to 16043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   title              16044 non-null  object        
 1   rating             16044 non-null  object        
 2   rental_rate        16044 non-null  float64       
 3   length             16044 non-null  int64         
 4   film_id            16044 non-null  int64         
 5   inventory_id       16044 non-null  int64         
 6   rental_id          16044 non-null  int64         
 7   rental_date        16044 non-null  datetime64[ns]
 8   return_date        15861 non-null  datetime64[ns]
 9   rented_last_month  16044 non-null  object        
dtypes: datetime64[ns](2), float64(1), int64(4), object(3)
memory usage: 1.2+ MB


In [9]:
df_2['rented_last_month'] = df_2['rented_last_month'].astype('int')
df_2['film_id'] = df_2['film_id'].astype('str')

In [10]:
df_2

title rating  rental_rate  length film_id  inventory_id  \
0      ACADEMY DINOSAUR     PG         0.99      86       1             1   
1      ACADEMY DINOSAUR     PG         0.99      86       1             1   
2      ACADEMY DINOSAUR     PG         0.99      86       1             1   
3      ACADEMY DINOSAUR     PG         0.99      86       1             2   
4      ACADEMY DINOSAUR     PG         0.99      86       1             2   
...                 ...    ...          ...     ...     ...           ...   
16039         ZORRO ARK  NC-17         4.99      50    1000          4581   
16040         ZORRO ARK  NC-17         4.99      50    1000          4581   
16041         ZORRO ARK  NC-17         4.99      50    1000          4581   
16042         ZORRO ARK  NC-17         4.99      50    1000          4581   
16043         ZORRO ARK  NC-17         4.99      50    1000          4581   

       rental_id         rental_date         return_date  rented_last_month  
0           4863 2005-07-08 19:03:15 2005-07-11 21:29:15                  0  
1          11433 2005-08-02 20:13:10 2005-08-11 21:35:10                  1  
2          14714 2005-08-21 21:27:43 2005-08-30 22:26:43                  1  
3            972 2005-05-30 20:21:07 2005-06-06 00:36:07                  0  
4           2117 2005-06-17 20:24:00 2005-06-23 17:45:00                  0  
...          ...                 ...                 ...                ...  
16039        711 2005-05-29 03:49:03 2005-05-31 08:29:03                  0  
16040       1493 2005-06-15 21:50:32 2005-06-17 01:02:32                  0  
16041       6712 2005-07-12 13:24:47 2005-07-20 09:35:47                  0  
16042       9701 2005-07-31 07:32:21 2005-08-01 05:07:21                  0  
16043      12894 2005-08-19 03:49:28 2005-08-25 01:51:28                  1  

[16044 rows x 10 columns]

In [11]:
df_2['rented_last_month'] = df_2['rented_last_month'].astype('bool')

In [12]:
#Analyze extracted features and transform them. You may need to encode some categorical variables, or scale numerical variables.

In [13]:
#dropping columns
df_2 = df_2.drop(['rental_date'], axis=1)
df_2 = df_2.drop(['return_date'], axis=1)
df_2 = df_2.drop(['inventory_id'], axis=1)
#df_2 = df_2.drop(['film_id'], axis=1)
df_2 = df_2.drop(['title'], axis=1)
df_2 = df_2.drop(['rental_id'], axis=1)


In [14]:
df_2.rented_last_month.value_counts()

rented_last_month
False    10358
True      5686
Name: count, dtype: int64

In [15]:
df_2.rating.value_counts()

rating
PG-13    3585
NC-17    3293
PG       3212
R        3181
G        2773
Name: count, dtype: int64

In [16]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16044 entries, 0 to 16043
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   rating             16044 non-null  object 
 1   rental_rate        16044 non-null  float64
 2   length             16044 non-null  int64  
 3   film_id            16044 non-null  object 
 4   rented_last_month  16044 non-null  bool   
dtypes: bool(1), float64(1), int64(1), object(2)
memory usage: 517.2+ KB


In [17]:
df_2

rating  rental_rate  length film_id  rented_last_month
0         PG         0.99      86       1              False
1         PG         0.99      86       1               True
2         PG         0.99      86       1               True
3         PG         0.99      86       1              False
4         PG         0.99      86       1              False
...      ...          ...     ...     ...                ...
16039  NC-17         4.99      50    1000              False
16040  NC-17         4.99      50    1000              False
16041  NC-17         4.99      50    1000              False
16042  NC-17         4.99      50    1000              False
16043  NC-17         4.99      50    1000               True

[16044 rows x 5 columns]

In [18]:
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, ConfusionMatrixDisplay, RocCurveDisplay
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore", category = DeprecationWarning)
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

In [19]:
X = df_2.iloc[:, :-1] # explanatory variables

y = df_2.iloc[:,-1] #  target variable

In [20]:
y.value_counts()/len(y)

rented_last_month
False    0.6456
True     0.3544
Name: count, dtype: float64

In [21]:
numeric_features = ['rental_rate', 'length']

categorical_features = ["rating",'film_id']

In [22]:
numeric_transformer = Pipeline(steps = [("imputer", SimpleImputer(strategy="mean")),("scaler", StandardScaler())])

categorical_transformer = OneHotEncoder(drop = "first") 

In [23]:
preprocessor = ColumnTransformer(
            transformers = [("numerical", numeric_transformer, numeric_features),
                            ("categorical", categorical_transformer, categorical_features)]
)


In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state =42)

In [25]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [26]:
encoder = LabelEncoder()

y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [27]:
#Create a logistic regression model to predict this variable from the cleaned data.


In [28]:
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [29]:
pred_train = classifier.predict(X_train)
display(pred_train)

pred_test = classifier.predict(X_test)
display(pred_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [30]:
prob_train = classifier.predict_proba(X_train)

display(prob_train)

prob_test = classifier.predict_proba(X_test)
display(prob_test)

array([[0.70351337, 0.29648663],
       [0.60296   , 0.39704   ],
       [0.68203602, 0.31796398],
       ...,
       [0.63615788, 0.36384212],
       [0.6266225 , 0.3733775 ],
       [0.61498927, 0.38501073]])

array([[0.69991777, 0.30008223],
       [0.75505392, 0.24494608],
       [0.45515518, 0.54484482],
       ...,
       [0.60290337, 0.39709663],
       [0.72327873, 0.27672127],
       [0.66288056, 0.33711944]])

In [31]:
print("accuracy on train set", accuracy_score(y_train, pred_train))
print("accuracy on test set", accuracy_score(y_test, pred_test))
print("f1 score on train set", f1_score(y_train, pred_train))
print("f1 score on test set", f1_score(y_test, pred_test))

accuracy on train set 0.6524557466965843
accuracy on test set 0.631762652705061
f1 score on train set 0.1102127659574468
f1 score on test set 0.04771115409413282


In [32]:
print(classification_report(y_train, pred_train))

print(classification_report(y_test, pred_test))

              precision    recall  f1-score   support

           0       0.65      0.98      0.78      7746
           1       0.63      0.06      0.11      4287

    accuracy                           0.65     12033
   macro avg       0.64      0.52      0.45     12033
weighted avg       0.64      0.65      0.54     12033

              precision    recall  f1-score   support

           0       0.65      0.96      0.77      2612
           1       0.24      0.03      0.05      1399

    accuracy                           0.63      4011
   macro avg       0.45      0.49      0.41      4011
weighted avg       0.51      0.63      0.52      4011



In [33]:
#Evaluate the results.